name: Release
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.4"
          otp-version: "23.2.6"
      - run: mix deps.get
      - run: mix release
