name: Release
on:
  push:
    branches: [ master ]

env:
  MIX_ENV: prod

jobs:
  deploy:
    runs-on: elixir-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install ZSTD
        run: sudo apt-get install zstd
      - name: Mix Dependencies
        run: mix deps.get
      - name: Mix Release
      - run: mix release
