name: Release
on:
  push:
    tags: ['v*.*.*']

env:
  MIX_ENV: prod

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: ZSTD
        run: sudo apt-get install zstd
      - name: Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.4"
          otp-version: "23.2.6"
      - name: Dependencies
        run: mix deps.get
      - name: Build
        run: mix release
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: _build/prod/rel/bakeware/notes
